In [16]:
import os
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from skimage import io, transform
import numpy as np

# Ganti dengan direktori yang berisi folder dataset
dataset_dir = 'G:\MK\SEMESTER 4\ML\\tugas1\Coding\Dataset'

# Inisialisasi daftar kelas dan label
classes = ['Bus', 'Car', 'Motorcycle', 'Truck']
labels = [0, 1, 2, 3]

X_train = []
y_train = []

# Load data training
for label, class_name in zip(labels, classes):
    class_dir = os.path.join(dataset_dir, class_name)
    
    # Untuk setiap gambar dalam kelas
    for image_name in os.listdir(class_dir):
        image_path = os.path.join(class_dir, image_name)
        
        # Ubah gambar menjadi ukuran yang sama
        image = io.imread(image_path, as_gray=True)
        image = transform.resize(image, (100, 100))  # Ubah ukuran gambar menjadi 100x100
        
        # Ubah gambar menjadi larik nilai piksel
        image_flattened = image.flatten()
        
        # Tambahkan gambar dan label kelas ke data training
        X_train.append(image_flattened)
        y_train.append(label)

X_train = np.array(X_train)
y_train = np.array(y_train)

print("Data Training (X_train):")
print(X_train)
print("Label Training (y_train):")
print(y_train)

# Inisialisasi model SVM
svm = SVC()

# Latih model SVM menggunakan data training
svm.fit(X_train, y_train)

# Inisialisasi model KNN
knn = KNeighborsClassifier()

# Latih model KNN menggunakan data training
knn.fit(X_train, y_train)

# Load data testing
X_test = []
y_test = []
test_dir = 'G:\MK\SEMESTER 4\ML\\tugas1\Coding\dataset_test'

# Untuk setiap gambar dalam folder testing
for image_name in os.listdir(test_dir):
    image_path = os.path.join(test_dir, image_name)
    
    # Ubah gambar menjadi ukuran yang sama
    image = io.imread(image_path, as_gray=True)
    image = transform.resize(image, (100, 100))  # Ubah ukuran gambar menjadi 100x100
    
    # Ubah gambar menjadi larik nilai piksel
    image_flattened = image.flatten()
    
    # Tambahkan gambar dan label kelas ke data testing
    X_test.append(image_flattened)
    # Tambahkan label dummy karena tidak diketahui
    y_test.append(-1)

X_test = np.array(X_test)
y_test = np.array(y_test)

# Prediksi kelas dari data testing menggunakan model SVM
y_pred_svm = svm.predict(X_test)

# Cetak hasil prediksi menggunakan model SVM
print("Hasil Prediksi (SVM):")
for i, pred in enumerate(y_pred_svm):
    class_name = classes[pred]
    print("Gambar", i+1, ": Prediksi =", class_name)

# Prediksi kelas dari data testing menggunakan model KNN
y_pred_knn = knn.predict(X_test)

# Cetak hasil prediksi menggunakan model KNN
print("Hasil Prediksi (KNN):")
for i, pred in enumerate(y_pred_knn):
    class_name = classes[pred]
    print("Gambar", i+1, ": Prediksi= ", class_name)

# Evaluasi akurasi model SVM
y_train_pred_svm = svm.predict(X_train)
train_accuracy_svm = accuracy_score(y_train, y_train_pred_svm)
print("Akurasi Model SVM (Data Training):", train_accuracy_svm)

# Evaluasi akurasi model KNN
y_train_pred_knn = knn.predict(X_train)
train_accuracy_knn = accuracy_score(y_train, y_train_pred_knn)
print("Akurasi Model KNN (Data Training):", train_accuracy_knn)

d:\Users\python\Lib\site-packages\PIL\Image.py:981: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(


Data Training (X_train):
[[0.95730902 0.95659289 0.95676477 ... 0.69970204 0.69957766 0.70280249]
 [0.81705104 0.81318168 0.8139376  ... 0.61630556 0.60944203 0.60711136]
 [0.13134347 0.18827715 0.11311003 ... 0.50154657 0.51065321 0.51556503]
 ...
 [0.58512521 0.59061786 0.60369031 ... 0.23132557 0.18620724 0.23474998]
 [0.82678473 0.818151   0.82313376 ... 0.04502157 0.04049337 0.03659838]
 [0.9963214  0.99690199 0.99682032 ... 0.99626236 0.99618996 0.99638302]]
Label Training (y_train):
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 